#!/bin/bash

echo "Stealth Checker ver 1.0"
echo " Stealth Check on Tamarin file"
echo " Developer : Anoymous"
echo " Email : "
echo "Executing parser....."

if test "$#" -ne 1; then
	echo "Illegal number of parameters: Only tamarin filename required"
	echo "usage: $(basename $0) <file_name> "
	echo "Exiting parser.... "
	echo "Try again...."
else
	rm ./stcheck*.spthy 
	
	for file in $1/*.spthy
	do
	  echo "working on file " $file
	  python3 stealthcheck.py $file
	done
	
 	echo "Starting stealth check...."
	tamarin-prover --prove stcheck*.spthy
fi

